import { Place } from '@/types/place';
import { CategoryId } from '@/constants/categories';

const MOCK_PLACES: Record<string, Place[]> = {
  'all': [],
  'restaurant': [],
  'park': [],
  'historical': [],
  'cafe': [],
  'entertainment': [],
  'shopping': [],
  'hotel': [],
};

// ==================== RESTAURANTS (10) ====================
const RESTAURANTS: Place[] = [
  {
    id: 'r1',
    name: 'Kolachi Restaurant',
    description: 'Famous sea-view restaurant serving authentic Pakistani and Continental cuisine',
    category: 'restaurant',
    rating: 4.5,
    totalRatings: 1250,
    imageUrl: 'https://picsum.photos/id/30/400/300',
    address: 'Do Darya, Karachi',
    priceLevel: 3,
    openingHours: '12:00 PM - 12:00 AM',
    phone: '+92 21 1234567',
  },
  {
    id: 'r2',
    name: 'Monal Restaurant',
    description: 'Rooftop restaurant with panoramic city views',
    category: 'restaurant',
    rating: 4.7,
    totalRatings: 980,
    imageUrl: 'https://picsum.photos/id/29/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 3,
    openingHours: '12:00 PM - 1:00 AM',
    phone: '+92 21 3456789',
  },
  {
    id: 'r3',
    name: 'Okra Restaurant',
    description: 'Fine dining restaurant known for Mediterranean and Continental cuisine',
    category: 'restaurant',
    rating: 4.8,
    totalRatings: 670,
    imageUrl: 'https://picsum.photos/id/127/400/300',
    address: 'DHA Phase 8, Karachi',
    priceLevel: 4,
    openingHours: '12:00 PM - 11:30 PM',
    phone: '+92 21 35894444',
  },
  {
    id: 'r4',
    name: 'BBQ Tonight',
    description: 'Famous barbecue restaurant with outdoor seating',
    category: 'restaurant',
    rating: 4.4,
    totalRatings: 2450,
    imageUrl: 'https://picsum.photos/id/120/400/300',
    address: 'Clifton Block 4, Karachi',
    priceLevel: 3,
    openingHours: '6:00 PM - 12:00 AM',
    phone: '+92 21 35302525',
  },
  {
    id: 'r5',
    name: 'Cafe Laziz',
    description: 'Traditional Pakistani cuisine with modern twist',
    category: 'restaurant',
    rating: 4.3,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/133/400/300',
    address: 'North Nazimabad, Karachi',
    priceLevel: 2,
    openingHours: '11:00 AM - 11:00 PM',
    phone: '+92 21 36628888',
  },
  {
    id: 'r6',
    name: 'Fuchsia Kitchen',
    description: 'Contemporary Asian fusion restaurant',
    category: 'restaurant',
    rating: 4.6,
    totalRatings: 540,
    imageUrl: 'https://picsum.photos/id/26/400/300',
    address: 'DHA Phase 5, Karachi',
    priceLevel: 4,
    openingHours: '12:00 PM - 11:00 PM',
    phone: '+92 21 35873333',
  },
  {
    id: 'r7',
    name: 'Ginsoy Chinese',
    description: 'Best Chinese cuisine in town',
    category: 'restaurant',
    rating: 4.2,
    totalRatings: 2100,
    imageUrl: 'https://picsum.photos/id/124/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 2,
    openingHours: '12:00 PM - 12:00 AM',
    phone: '+92 21 34812345',
  },
  {
    id: 'r8',
    name: 'Xanders',
    description: 'International cuisine with live music',
    category: 'restaurant',
    rating: 4.5,
    totalRatings: 760,
    imageUrl: 'https://picsum.photos/id/40/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 4,
    openingHours: '12:00 PM - 2:00 AM',
    phone: '+92 21 35308888',
  },
  {
    id: 'r9',
    name: 'Salt\'n Pepper Village',
    description: 'Authentic Pakistani village theme restaurant',
    category: 'restaurant',
    rating: 4.6,
    totalRatings: 1850,
    imageUrl: 'https://picsum.photos/id/94/400/300',
    address: 'Shahrah-e-Faisal, Karachi',
    priceLevel: 3,
    openingHours: '7:00 PM - 12:00 AM',
    phone: '+92 21 32780567',
  },
  {
    id: 'r10',
    name: 'The Patio',
    description: 'Italian cuisine with beautiful outdoor seating',
    category: 'restaurant',
    rating: 4.7,
    totalRatings: 430,
    imageUrl: 'https://picsum.photos/id/36/400/300',
    address: 'DHA Phase 5, Karachi',
    priceLevel: 4,
    openingHours: '12:00 PM - 11:00 PM',
    phone: '+92 21 35375555',
  },
];

// ==================== PARKS (10) ====================
const PARKS: Place[] = [
  {
    id: 'p1',
    name: 'Beach View Park',
    description: 'Beautiful seaside park with walking trails and picnic areas',
    category: 'park',
    rating: 4.3,
    totalRatings: 560,
    imageUrl: 'https://picsum.photos/id/15/400/300',
    address: 'Clifton Beach, Karachi',
    openingHours: '6:00 AM - 10:00 PM',
  },
  {
    id: 'p2',
    name: 'Hill Park',
    description: 'Popular urban park with jogging tracks and family areas',
    category: 'park',
    rating: 4.2,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/13/400/300',
    address: 'PECHS, Karachi',
    openingHours: '5:00 AM - 10:00 PM',
  },
  {
    id: 'p3',
    name: 'Baghdad Ibn-e-Rashid Park',
    description: 'Large park with sports facilities and children play area',
    category: 'park',
    rating: 4.4,
    totalRatings: 670,
    imageUrl: 'https://picsum.photos/id/42/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    openingHours: '6:00 AM - 9:00 PM',
  },
  {
    id: 'p4',
    name: 'Jheel Park',
    description: 'Park with beautiful lake and boating facility',
    category: 'park',
    rating: 4.5,
    totalRatings: 720,
    imageUrl: 'https://picsum.photos/id/143/400/300',
    address: 'DHA Phase 8, Karachi',
    openingHours: '8:00 AM - 8:00 PM',
  },
  {
    id: 'p5',
    name: 'Aziz Bhatti Park',
    description: 'Well-maintained park with walking track',
    category: 'park',
    rating: 4.1,
    totalRatings: 450,
    imageUrl: 'https://picsum.photos/id/71/400/300',
    address: 'North Karachi, Karachi',
    openingHours: '5:00 AM - 9:00 PM',
  },
  {
    id: 'p6',
    name: 'Kidney Hill Park',
    description: 'Scenic park with hiking trails',
    category: 'park',
    rating: 4.6,
    totalRatings: 380,
    imageUrl: 'https://picsum.photos/id/96/400/300',
    address: 'Clifton, Karachi',
    openingHours: '7:00 AM - 6:00 PM',
  },
  {
    id: 'p7',
    name: 'Askari Park',
    description: 'Family-friendly park with amusement rides',
    category: 'park',
    rating: 4.3,
    totalRatings: 920,
    imageUrl: 'https://picsum.photos/id/24/400/300',
    address: 'Askari IV, Karachi',
    openingHours: '4:00 PM - 10:00 PM',
  },
  {
    id: 'p8',
    name: 'Safari Park',
    description: 'Wildlife safari park with animal enclosures',
    category: 'park',
    rating: 4.4,
    totalRatings: 1150,
    imageUrl: 'https://picsum.photos/id/17/400/300',
    address: 'Gulshan-e-Maymar, Karachi',
    openingHours: '9:00 AM - 6:00 PM',
    phone: '+92 21 36362222',
  },
  {
    id: 'p9',
    name: 'Nisar Shaheed Park',
    description: 'Peaceful park with fountains',
    category: 'park',
    rating: 4.0,
    totalRatings: 310,
    imageUrl: 'https://picsum.photos/id/44/400/300',
    address: 'Nazimabad, Karachi',
    openingHours: '6:00 AM - 8:00 PM',
  },
  {
    id: 'p10',
    name: 'Timber Pond Park',
    description: 'Park with natural pond and bird watching',
    category: 'park',
    rating: 4.2,
    totalRatings: 290,
    imageUrl: 'https://picsum.photos/id/47/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    openingHours: '7:00 AM - 7:00 PM',
  },
];

// ==================== HISTORICAL (10) ====================
const HISTORICAL: Place[] = [
  {
    id: 'h1',
    name: 'Mohatta Palace',
    description: 'Historic palace museum showcasing art and cultural heritage',
    category: 'historical',
    rating: 4.6,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/96/400/300',
    address: 'Clifton, Karachi',
    openingHours: '10:00 AM - 6:00 PM (Closed Monday)',
    phone: '+92 21 35837671',
  },
  {
    id: 'h2',
    name: 'Quaid-e-Azam House Museum',
    description: 'Historical residence of Pakistan\'s founder, now a museum',
    category: 'historical',
    rating: 4.7,
    totalRatings: 750,
    imageUrl: 'https://picsum.photos/id/104/400/300',
    address: 'Fatima Jinnah Road, Karachi',
    openingHours: '9:00 AM - 5:00 PM',
    phone: '+92 21 99261376',
  },
  {
    id: 'h3',
    name: 'National Museum of Pakistan',
    description: 'Extensive museum showcasing Pakistani art, history, and culture',
    category: 'historical',
    rating: 4.5,
    totalRatings: 620,
    imageUrl: 'https://picsum.photos/id/10/400/300',
    address: 'Burns Garden, Karachi',
    openingHours: '10:00 AM - 5:00 PM (Closed Friday)',
    phone: '+92 21 99261365',
  },
  {
    id: 'h4',
    name: 'Frere Hall',
    description: 'Venetian Gothic-style building from British era',
    category: 'historical',
    rating: 4.4,
    totalRatings: 540,
    imageUrl: 'https://picsum.photos/id/1/400/300',
    address: 'Civil Lines, Karachi',
    openingHours: '9:00 AM - 5:00 PM',
  },
  {
    id: 'h5',
    name: 'Empress Market',
    description: 'Historic market built during British rule',
    category: 'historical',
    rating: 4.2,
    totalRatings: 1250,
    imageUrl: 'https://picsum.photos/id/39/400/300',
    address: 'Saddar, Karachi',
    openingHours: '8:00 AM - 8:00 PM',
  },
  {
    id: 'h6',
    name: 'Mazar-e-Quaid',
    description: 'Mausoleum of Pakistan\'s founder Muhammad Ali Jinnah',
    category: 'historical',
    rating: 4.9,
    totalRatings: 3450,
    imageUrl: 'https://picsum.photos/id/11/400/300',
    address: 'Jamshed Quarters, Karachi',
    openingHours: '24/7',
  },
  {
    id: 'h7',
    name: 'Chaukhandi Tombs',
    description: 'Ancient burial site with intricate sandstone carvings',
    category: 'historical',
    rating: 4.5,
    totalRatings: 420,
    imageUrl: 'https://picsum.photos/id/57/400/300',
    address: 'National Highway, Karachi',
    openingHours: '8:00 AM - 6:00 PM',
  },
  {
    id: 'h8',
    name: 'Wazir Mansion',
    description: 'Birthplace of Quaid-e-Azam Muhammad Ali Jinnah',
    category: 'historical',
    rating: 4.7,
    totalRatings: 380,
    imageUrl: 'https://picsum.photos/id/85/400/300',
    address: 'Kharadar, Karachi',
    openingHours: '9:00 AM - 5:00 PM',
  },
  {
    id: 'h9',
    name: 'Khaliq Deena Hall',
    description: 'Historical library and community hall',
    category: 'historical',
    rating: 4.3,
    totalRatings: 290,
    imageUrl: 'https://picsum.photos/id/12/400/300',
    address: 'MA Jinnah Road, Karachi',
    openingHours: '10:00 AM - 6:00 PM',
  },
  {
    id: 'h10',
    name: 'Karachi Port Trust Building',
    description: 'Colonial-era building with stunning architecture',
    category: 'historical',
    rating: 4.4,
    totalRatings: 310,
    imageUrl: 'https://picsum.photos/id/34/400/300',
    address: 'Port of Karachi, Karachi',
    openingHours: '9:00 AM - 5:00 PM',
  },
];

// ==================== CAFES (10) ====================
const CAFES: Place[] = [
  {
    id: 'c1',
    name: 'Baghdad Ice Cream',
    description: 'Historic ice cream parlor since 1953, famous for its unique flavors',
    category: 'cafe',
    rating: 4.8,
    totalRatings: 3200,
    imageUrl: 'https://picsum.photos/id/20/400/300',
    address: 'Saddar, Karachi',
    priceLevel: 1,
    openingHours: '10:00 AM - 11:00 PM',
    phone: '+92 21 7654321',
  },
  {
    id: 'c2',
    name: 'Espresso Coffee Shop',
    description: 'Cozy cafe serving specialty coffees and desserts',
    category: 'cafe',
    rating: 4.5,
    totalRatings: 560,
    imageUrl: 'https://picsum.photos/id/22/400/300',
    address: 'DHA Phase 5, Karachi',
    priceLevel: 2,
    openingHours: '8:00 AM - 11:00 PM',
    phone: '+92 21 35873333',
  },
  {
    id: 'c3',
    name: 'Chai Shai Cafe',
    description: 'Trendy cafe known for Pakistani chai varieties and snacks',
    category: 'cafe',
    rating: 4.6,
    totalRatings: 1430,
    imageUrl: 'https://picsum.photos/id/169/400/300',
    address: 'Khayaban-e-Muslim, Karachi',
    priceLevel: 1,
    openingHours: '11:00 AM - 1:00 AM',
    phone: '+92 333 1234567',
  },
  {
    id: 'c4',
    name: 'Butlers Chocolate Cafe',
    description: 'Premium chocolate and coffee cafe',
    category: 'cafe',
    rating: 4.7,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/23/400/300',
    address: 'Dolmen Mall, Karachi',
    priceLevel: 3,
    openingHours: '10:00 AM - 10:00 PM',
  },
  {
    id: 'c5',
    name: 'Coffee Wagera',
    description: 'Popular local coffee chain',
    category: 'cafe',
    rating: 4.4,
    totalRatings: 1560,
    imageUrl: 'https://picsum.photos/id/18/400/300',
    address: 'Multiple Locations, Karachi',
    priceLevel: 2,
    openingHours: '9:00 AM - 12:00 AM',
  },
  {
    id: 'c6',
    name: 'Mocca Coffee',
    description: 'Cozy atmosphere with great coffee',
    category: 'cafe',
    rating: 4.5,
    totalRatings: 670,
    imageUrl: 'https://picsum.photos/id/28/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 2,
    openingHours: '8:00 AM - 11:00 PM',
  },
  {
    id: 'c7',
    name: 'Gloria Jeans',
    description: 'International coffee chain',
    category: 'cafe',
    rating: 4.3,
    totalRatings: 1100,
    imageUrl: 'https://picsum.photos/id/37/400/300',
    address: 'Multiple Locations, Karachi',
    priceLevel: 2,
    openingHours: '9:00 AM - 11:00 PM',
  },
  {
    id: 'c8',
    name: 'The Second Cup',
    description: 'Canadian coffee brand',
    category: 'cafe',
    rating: 4.4,
    totalRatings: 780,
    imageUrl: 'https://picsum.photos/id/45/400/300',
    address: 'DHA, Karachi',
    priceLevel: 2,
    openingHours: '8:00 AM - 10:00 PM',
  },
  {
    id: 'c9',
    name: 'Chotu Chai Wala',
    description: 'Famous street chai spot',
    category: 'cafe',
    rating: 4.9,
    totalRatings: 2900,
    imageUrl: 'https://picsum.photos/id/25/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 1,
    openingHours: '5:00 PM - 2:00 AM',
  },
  {
    id: 'c10',
    name: 'Del Frio',
    description: 'Ice cream and dessert cafe',
    category: 'cafe',
    rating: 4.5,
    totalRatings: 950,
    imageUrl: 'https://picsum.photos/id/68/400/300',
    address: 'North Nazimabad, Karachi',
    priceLevel: 1,
    openingHours: '12:00 PM - 12:00 AM',
  },
];

// ==================== ENTERTAINMENT (10) ====================
const ENTERTAINMENT: Place[] = [
  {
    id: 'e1',
    name: 'Port Grand',
    description: 'Waterfront entertainment and dining complex with stunning harbor views',
    category: 'entertainment',
    rating: 4.6,
    totalRatings: 3450,
    imageUrl: 'https://picsum.photos/id/31/400/300',
    address: 'Port of Karachi, Karachi',
    priceLevel: 3,
    openingHours: '4:00 PM - 2:00 AM',
    phone: '+92 21 38683678',
  },
  {
    id: 'e2',
    name: 'Arena Entertainment',
    description: 'Massive indoor entertainment center with bowling, arcade, and rides',
    category: 'entertainment',
    rating: 4.4,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/26/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 3,
    openingHours: '12:00 PM - 12:00 AM',
    phone: '+92 21 34823456',
  },
  {
    id: 'e3',
    name: 'Karachi Zoo',
    description: 'Historic zoo with diverse animal species and family attractions',
    category: 'entertainment',
    rating: 4.1,
    totalRatings: 2340,
    imageUrl: 'https://picsum.photos/id/129/400/300',
    address: 'Garden East, Karachi',
    openingHours: '9:00 AM - 6:00 PM',
    phone: '+92 21 99261400',
  },
  {
    id: 'e4',
    name: 'Joyland',
    description: 'Amusement park with thrilling rides',
    category: 'entertainment',
    rating: 4.3,
    totalRatings: 1560,
    imageUrl: 'https://picsum.photos/id/33/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 2,
    openingHours: '2:00 PM - 10:00 PM',
  },
  {
    id: 'e5',
    name: 'Cineplex Cinema',
    description: 'Modern cinema with latest movies',
    category: 'entertainment',
    rating: 4.5,
    totalRatings: 2100,
    imageUrl: 'https://picsum.photos/id/2/400/300',
    address: 'Dolmen Mall, Karachi',
    priceLevel: 2,
    openingHours: '10:00 AM - 12:00 AM',
  },
  {
    id: 'e6',
    name: 'Beach Luxury Water Park',
    description: 'Water park with slides and pools',
    category: 'entertainment',
    rating: 4.2,
    totalRatings: 980,
    imageUrl: 'https://picsum.photos/id/50/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 2,
    openingHours: '10:00 AM - 6:00 PM',
  },
  {
    id: 'e7',
    name: 'Paintball Arena',
    description: 'Adventure sports with paintball',
    category: 'entertainment',
    rating: 4.6,
    totalRatings: 540,
    imageUrl: 'https://picsum.photos/id/59/400/300',
    address: 'DHA Phase 8, Karachi',
    priceLevel: 3,
    openingHours: '2:00 PM - 10:00 PM',
  },
  {
    id: 'e8',
    name: 'Go Karting Arena',
    description: 'High-speed go-karting track',
    category: 'entertainment',
    rating: 4.7,
    totalRatings: 430,
    imageUrl: 'https://picsum.photos/id/49/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 3,
    openingHours: '3:00 PM - 11:00 PM',
  },
  {
    id: 'e9',
    name: 'The Arkadians',
    description: 'Bowling and gaming zone',
    category: 'entertainment',
    rating: 4.4,
    totalRatings: 760,
    imageUrl: 'https://picsum.photos/id/46/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 2,
    openingHours: '12:00 PM - 12:00 AM',
  },
  {
    id: 'e10',
    name: 'Fun Dungeon',
    description: 'Indoor soft play area for kids',
    category: 'entertainment',
    rating: 4.3,
    totalRatings: 580,
    imageUrl: 'https://picsum.photos/id/54/400/300',
    address: 'DHA, Karachi',
    priceLevel: 2,
    openingHours: '11:00 AM - 9:00 PM',
  },
];

// ==================== SHOPPING (10) ====================
const SHOPPING: Place[] = [
  {
    id: 's1',
    name: 'Dolmen Mall',
    description: 'Premium shopping mall with international and local brands',
    category: 'shopping',
    rating: 4.4,
    totalRatings: 2100,
    imageUrl: 'https://picsum.photos/id/107/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 3,
    openingHours: '11:00 AM - 11:00 PM',
  },
  {
    id: 's2',
    name: 'Lucky One Mall',
    description: 'One of Karachi\'s largest shopping malls with cinema and food court',
    category: 'shopping',
    rating: 4.5,
    totalRatings: 3100,
    imageUrl: 'https://picsum.photos/id/179/400/300',
    address: 'Rashid Minhas Road, Karachi',
    priceLevel: 3,
    openingHours: '11:00 AM - 11:00 PM',
    phone: '+92 21 111 111 222',
  },
  {
    id: 's3',
    name: 'Ocean Mall',
    description: 'Luxury shopping mall with panoramic sea views',
    category: 'shopping',
    rating: 4.7,
    totalRatings: 2780,
    imageUrl: 'https://picsum.photos/id/108/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 4,
    openingHours: '11:00 AM - 11:00 PM',
    phone: '+92 21 35312345',
  },
  {
    id: 's4',
    name: 'Park Towers',
    description: 'Upscale shopping complex',
    category: 'shopping',
    rating: 4.3,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/82/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 3,
    openingHours: '11:00 AM - 10:00 PM',
  },
  {
    id: 's5',
    name: 'Millennium Mall',
    description: 'Modern shopping destination',
    category: 'shopping',
    rating: 4.4,
    totalRatings: 670,
    imageUrl: 'https://picsum.photos/id/84/400/300',
    address: 'Gulshan-e-Iqbal, Karachi',
    priceLevel: 3,
    openingHours: '11:00 AM - 10:00 PM',
  },
  {
    id: 's6',
    name: 'Atrium Mall',
    description: 'Shopping mall with variety of stores',
    category: 'shopping',
    rating: 4.2,
    totalRatings: 540,
    imageUrl: 'https://picsum.photos/id/99/400/300',
    address: 'Saddar, Karachi',
    priceLevel: 2,
    openingHours: '10:00 AM - 9:00 PM',
  },
  {
    id: 's7',
    name: 'Nearest Mall',
    description: 'Convenient shopping center',
    category: 'shopping',
    rating: 4.1,
    totalRatings: 430,
    imageUrl: 'https://picsum.photos/id/86/400/300',
    address: 'North Nazimabad, Karachi',
    priceLevel: 2,
    openingHours: '10:00 AM - 10:00 PM',
  },
  {
    id: 's8',
    name: 'Zainab Market',
    description: 'Famous market for clothing and accessories',
    category: 'shopping',
    rating: 4.0,
    totalRatings: 1450,
    imageUrl: 'https://picsum.photos/id/62/400/300',
    address: 'Saddar, Karachi',
    priceLevel: 1,
    openingHours: '11:00 AM - 8:00 PM',
  },
  {
    id: 's9',
    name: 'Tariq Road Shopping',
    description: 'Famous shopping street with brand outlets',
    category: 'shopping',
    rating: 4.3,
    totalRatings: 1890,
    imageUrl: 'https://picsum.photos/id/76/400/300',
    address: 'Tariq Road, Karachi',
    priceLevel: 2,
    openingHours: '11:00 AM - 10:00 PM',
  },
  {
    id: 's10',
    name: 'Hyperstar',
    description: 'Large hypermarket for all needs',
    category: 'shopping',
    rating: 4.5,
    totalRatings: 2340,
    imageUrl: 'https://picsum.photos/id/95/400/300',
    address: 'Multiple Locations, Karachi',
    priceLevel: 2,
    openingHours: '9:00 AM - 11:00 PM',
  },
];

// ==================== HOTELS (10) ====================
const HOTELS: Place[] = [
  {
    id: 'hot1',
    name: 'Pearl Continental Hotel',
    description: 'Luxury 5-star hotel with premium amenities and multiple dining options',
    category: 'hotel',
    rating: 4.7,
    totalRatings: 2100,
    imageUrl: 'https://picsum.photos/id/106/400/300',
    address: 'Club Road, Karachi',
    priceLevel: 4,
    openingHours: '24/7',
    phone: '+92 21 35688000',
  },
  {
    id: 'hot2',
    name: 'Avari Tower Hotel',
    description: 'Iconic 5-star hotel with business facilities and rooftop pool',
    category: 'hotel',
    rating: 4.6,
    totalRatings: 1870,
    imageUrl: 'https://picsum.photos/id/41/400/300',
    address: 'Fatima Jinnah Road, Karachi',
    priceLevel: 4,
    openingHours: '24/7',
    phone: '+92 21 35680100',
  },
  {
    id: 'hot3',
    name: 'Movenpick Hotel',
    description: 'International 5-star hotel with excellent service',
    category: 'hotel',
    rating: 4.7,
    totalRatings: 1450,
    imageUrl: 'https://picsum.photos/id/77/400/300',
    address: 'Club Road, Karachi',
    priceLevel: 4,
    openingHours: '24/7',
    phone: '+92 21 35668888',
  },
  {
    id: 'hot4',
    name: 'Regent Plaza Hotel',
    description: 'Business hotel with conference facilities',
    category: 'hotel',
    rating: 4.3,
    totalRatings: 890,
    imageUrl: 'https://picsum.photos/id/69/400/300',
    address: 'Shahrah-e-Faisal, Karachi',
    priceLevel: 3,
    openingHours: '24/7',
    phone: '+92 21 32780000',
  },
  {
    id: 'hot5',
    name: 'Hotel Mehran',
    description: 'Budget-friendly hotel with basic amenities',
    category: 'hotel',
    rating: 4.0,
    totalRatings: 650,
    imageUrl: 'https://picsum.photos/id/60/400/300',
    address: 'Shahrah-e-Faisal, Karachi',
    priceLevel: 2,
    openingHours: '24/7',
    phone: '+92 21 32788888',
  },
  {
    id: 'hot6',
    name: 'Ramada Plaza',
    description: 'Comfortable 4-star hotel',
    category: 'hotel',
    rating: 4.4,
    totalRatings: 780,
    imageUrl: 'https://picsum.photos/id/66/400/300',
    address: 'DHA Phase 8, Karachi',
    priceLevel: 3,
    openingHours: '24/7',
    phone: '+92 21 37123456',
  },
  {
    id: 'hot7',
    name: 'Beach Luxury Hotel',
    description: 'Seaside hotel with great views',
    category: 'hotel',
    rating: 4.2,
    totalRatings: 560,
    imageUrl: 'https://picsum.photos/id/70/400/300',
    address: 'Clifton, Karachi',
    priceLevel: 3,
    openingHours: '24/7',
    phone: '+92 21 35870000',
  },
  {
    id: 'hot8',
    name: 'Hotel Sarawan',
    description: 'Mid-range hotel with good location',
    category: 'hotel',
    rating: 4.1,
    totalRatings: 430,
    imageUrl: 'https://picsum.photos/id/73/400/300',
    address: 'Saddar, Karachi',
    priceLevel: 2,
    openingHours: '24/7',
    phone: '+92 21 32720000',
  },
  {
    id: 'hot9',
    name: 'Inn Hotel',
    description: 'Boutique hotel with modern rooms',
    category: 'hotel',
    rating: 4.5,
    totalRatings: 320,
    imageUrl: 'https://picsum.photos/id/81/400/300',
    address: 'DHA, Karachi',
    priceLevel: 3,
    openingHours: '24/7',
    phone: '+92 21 35880000',
  },
  {
    id: 'hot10',
    name: 'Airport Hotel',
    description: 'Convenient hotel near airport',
    category: 'hotel',
    rating: 4.2,
    totalRatings: 540,
    imageUrl: 'https://picsum.photos/id/88/400/300',
    address: 'Airport Road, Karachi',
    priceLevel: 2,
    openingHours: '24/7',
    phone: '+92 21 34567890',
  },
];

// Combine all data
MOCK_PLACES['all'] = [
  ...RESTAURANTS,
  ...PARKS,
  ...HISTORICAL,
  ...CAFES,
  ...ENTERTAINMENT,
  ...SHOPPING,
  ...HOTELS,
];

MOCK_PLACES['restaurant'] = RESTAURANTS;
MOCK_PLACES['park'] = PARKS;
MOCK_PLACES['historical'] = HISTORICAL;
MOCK_PLACES['cafe'] = CAFES;
MOCK_PLACES['entertainment'] = ENTERTAINMENT;
MOCK_PLACES['shopping'] = SHOPPING;
MOCK_PLACES['hotel'] = HOTELS;

export const fetchPlaces = async (category: CategoryId = 'all'): Promise<Place[]> => {
  // Simulate network delay for loading indicator demo
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  // Simulate random error (10% chance) to test error handling
  const shouldError = Math.random() < 0.1;
  if (shouldError) {
    throw new Error('Network connection failed. Please check your internet and try again.');
  }
  
  const places = MOCK_PLACES[category] || MOCK_PLACES['all'];
  
  // Sort by rating
  return places.sort((a, b) => b.rating - a.rating);
};

export const fetchPlaceById = async (id: string): Promise<Place | null> => {
  await new Promise(resolve => setTimeout(resolve, 800));
  
  const allPlaces = MOCK_PLACES['all'];
  const place = allPlaces.find(p => p.id === id);
  
  if (!place) {
    throw new Error('Place not found');
  }
  
  return place;
};